runmode: debug               # 开发模式, debug, release, test
addr: :9091                  # HTTP绑定端口
url: http://127.0.0.1:9091   # pingServer函数请求的API服务器的ip:port
max_check_count: 10           # pingServer函数尝试的次数
database:
  dbname: devops
  host: 192.168.100.51
  Port: 32336
  username: root
  password: Gdy7zlxQTx
wx_app_id: 123
wx_secret: 123